# Generated by Django 4.1 on 2022-08-24 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="account",
            old_name="id",
            new_name="seller_id",
        ),
    ]
